apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: hookla
  description: Webhook relay service - converts provider webhooks into Discord embeds.
  annotations:
    github.com/project-slug: widgetbot-io/hookla
    backstage.io/techdocs-ref: dir:.
    backstage.io/kubernetes-id: hookla
  links:
    - url: https://github.com/widgetbot-io/hookla
      title: Source
      icon: github
  tags:
    - widgetbot
    - scala
spec:
  type: service
  lifecycle: production
  owner: group:widgetbot
  system: widgetbot
