name: Docker
on:
  push:
    branches:
      - develop
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v10
      - name: Clean any left-over files
        run: sbt clean
      - name: Login to docker
        run: echo ${{ secrets.PAT }} | docker login ghcr.io --username yomanz --password-stdin
      - name: Compile the project and prepare docker files
        run: |
          sbt version
          sbt compile
          sbt docker:stage
          ls -la
          cd target/docker/stage
          ls -la
          docker build -t ghcr.io/widgetbot-io/hookla:${{github.sha}} .
          docker push ghcr.io/widgetbot-io/hookla:${{github.sha}}
#      - name: Build the DockerFile
#        run: docker build -t ghcr.io/widgetbot-io/hookla:${{github.sha}} target/docker/stage
#      - name: Push the Docker image
#        run: docker push ghcr.io/widgetbot-io/hookla:${{github.sha}}