name: Docker
on:
  push:
    branches:
      - develop
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v10
      - name: Clean any left-over files
        run: sbt clean
      - name: Login to docker
        run: echo ${{ secrets.PAT }} | docker login ghcr.io --username yomanz --password-stdin
      - name: Compile the project and push the docker image
        run: |
          sbt version
          sbt compile
          sbt docker:stage
          cd target/docker/stage
          docker build -t ghcr.io/widgetbot-io/hookla:${{github.sha}} -t ghcr.io/widgetbot-io/hookla:latest .
          docker push ghcr.io/widgetbot-io/hookla:${{github.sha}}
          docker push ghcr.io/widgetbot-io/hookla:latest