name: Docker
on:
  push:
    branches:
      - develop
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Clean any left-over files
        run: sbt clean
      - name: Compile the project and prepare docker files
        run: |
          sbt compile
          sbt docker:stage
      - name: Build the DockerFile
        run: docker build -t ghcr.io/widgetbot-io/hookla:${{github.sha}} .
        working-directory: ./target/docker/stage
      - name: Push the Docker image
        run: docker push ghcr.io/widgetbot-io/hookla:${{github.sha}}